configfile: "config.yaml"
configfile: "wsi_names.yaml"

from pathlib import Path

source_dir = config["source"]
dest_dir = config["dest"]
filenames = config["names"]


rule all:
    input:
        expand(dest_dir + "{filename}.zarr/.zgroup", filename=filenames)

rule convert_to_zarr:
    input: source_dir + "{filename}.tif"
    output: dest_dir + "{filename}.zarr/.zgroup"
    conda: "theremia"
    params: real_output=lambda wc: dest_dir + wc.filename + ".zarr",
            command="""aws s3 cp --metadata '{"touched":"now"}'"""
    threads: 8
    shell: "python convert_to_zarr.py --input {input} --output {params.real_output} && {params.command} {output} {output}"
